"""Add ip_address to user_check_request

Revision ID: 0aa067f0a25d
Revises: 8bb15801edc1
Create Date: 2025-03-24 20:09:52.199270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa067f0a25d'
down_revision: Union[str, None] = '8bb15801edc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_check_request', sa.Column('ip_address', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_check_request', 'ip_address')
    # ### end Alembic commands ###
