"""add ip adress pagevisit

Revision ID: 47fa278ba18c
Revises: 0aa067f0a25d
Create Date: 2025-03-24 22:14:23.068671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47fa278ba18c'
down_revision: Union[str, None] = '0aa067f0a25d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_visit', sa.Column('ip_address', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_visit', 'ip_address')
    # ### end Alembic commands ###
