"""add kaspi_pay_request model

Revision ID: 89845e3a3215
Revises: 807141ae837c
Create Date: 2025-03-17 19:36:25.344646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89845e3a3215'
down_revision: Union[str, None] = '807141ae837c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kaspi_pay_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('txn_id', sa.String(length=512), nullable=False, comment='ID в системе каспи'),
    sa.Column('account', sa.String(length=512), nullable=False, comment='Лицевой счет квартиры'),
    sa.Column('date', sa.DateTime(), nullable=False, comment='Дата запроса в системе каспи'),
    sa.Column('summ', sa.String(length=512), nullable=False, comment='Сумма пополнения'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('txn_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kaspi_pay_request')
    # ### end Alembic commands ###
